---
kind: pipeline
type: kubernetes
name: default

steps:
  - 
    name: build golang image
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      dockerfile: Dockerfile-golang
      registry: registry.0x42.in
      username: 
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo: registry.0x42.in/terrence/golang
      tags: 
        - 1.24-alpine3.21
        - ${DRONE_COMMIT_SHA}
        - latest
      platforms: 
        - linux/arm64
        - linux/amd64
    when:
      branch:
        - main
      event:
        - push
  -
    name: build base image
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      dockerfile: Dockerfile-base
      registry: registry.0x42.in
      username: 
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo: registry.0x42.in/terrence/base
      tags: 
        - alpine3.21
        - ${DRONE_COMMIT_SHA}
        - latest
      platforms: 
        - linux/arm64
        - linux/amd64
    when:
      branch:
        - main
      event:
        - push
  -
    name: build tofu image
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      dockerfile: Dockerfile-base
      registry: registry.0x42.in
      username: 
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo: registry.0x42.in/terrence/tofu
      tags: 
        - 1.9.1-alpine3.21
        - ${DRONE_COMMIT_SHA}
        - latest
      platforms: 
        - linux/arm64
        - linux/amd64
    when:
      branch:
        - main
      event:
        - push
  -
    name: test tofu image
    image: registry.0x42.in/terrence/tofu:1.9.1-alpine3.21
    commands:
      - tofu version

---
kind: signature
hmac: 3aae6f92393e3570ade3cddc323dbc7c3205522356272cea7f4bedbcf09ed146

...
